<a href="https://colab.research.google.com/github/HairuoGao029/MasterThesis/blob/main/gen_adj_mx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from xml.sax import parse, handler
import matplotlib.pyplot as plt
import pickle

from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My Drive

Mounted at /content/drive
/content/drive/My Drive


In [ ]:
lane_list = np.load('/content/drive/MyDrive/MSc/net/lane_list.npy')
lane_list = lane_list.tolist()

In [ ]:
class DetectorParse(handler.ContentHandler):
    """reading in the dataset from xml file
    """
    def __init__(self):
        self.adj_mx = np.eye(len(lane_list), dtype = np.float32)

    def startElement(self, name, attrs):
        if name == 'connection':
            fromedge = attrs['from']
            toedge = attrs['to']
            fromlane = attrs['from']+'_'+attrs['fromLane']
            tolane = attrs['to']+'_'+attrs['toLane']
            a = 7
            b = range(a)
            c = 3
            d = range(c)
            # connection between edges
            for i in reversed(b):
                if tolane+'%0' in lane_list:
                    if fromlane+'%'+str(i) in lane_list:
                        in_fromlane = lane_list.index(fromlane+'%'+str(i))
                        in_tolane = lane_list.index(tolane+'%0')
                        self.adj_mx[in_fromlane][in_tolane] = 1.00
                        break
            # connection in edges
            for i in reversed(b):
              for j in reversed(d):
                if fromedge+'_'+str(j)+'%'+str(i) in lane_list:
                  in_from = lane_list.index(fromedge+'_'+str(j)+'%'+str(i))
                  if fromedge+'_'+str(j+1)+'%'+str(i) in lane_list:      
                    in_to = lane_list.index(fromedge+'_'+str(j+1)+'%'+str(i))
                    self.adj_mx[in_from][in_to] = 1
                  if fromedge+'_'+str(j)+'%'+str(i+1) in lane_list:
                    in_to = lane_list.index(fromedge+'_'+str(j)+'%'+str(i+1))
                    self.adj_mx[in_from][in_to] = 1
                  if fromedge+'_'+str(j+1)+'%'+str(i+1) in lane_list:
                    in_to = lane_list.index(fromedge+'_'+str(j+1)+'%'+str(i+1))
                    self.adj_mx[in_from][in_to] = 1
        
    def endDocument(self):
        print(self.adj_mx)

In [ ]:
detector_output = DetectorParse()
parse('/content/drive/MyDrive/MSc/net/net.xml', detector_output) # reading in the dataset from xml file

# Save
with open('/content/drive/MyDrive/MSc/net/adj_mx_0.pkl', 'wb') as f:
    pickle.dump([detector_output.adj_mx[0], detector_output.adj_mx[0], detector_output.adj_mx], f, protocol=2)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
# lane_list # Retain only selected 630 sections
load_npy = np.load('/content/drive/MyDrive/MSc/datasets/averagespeed/0617/d16.npy', allow_pickle=True)

lane_list = []
for i in range(len(load_npy)):  
  data = data_raw[i][1]
  if(len(data))==720:
    lane_list.append(load_npy[i][0])
'''
lane_list = []
for key in load_dict_1:
  if  key[0] != ':':
    lane_list.append(key)
'''
print(len(lane_list))

np.save('/content/drive/MyDrive/MSc/net/lane_list.npy', lane_list)

630
