In [1]:
import numpy as np
from xml.sax import parse, handler
import matplotlib.pyplot as plt
import pickle

from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My Drive

Mounted at /content/drive
/content/drive/My Drive


In [16]:
lane_list = np.load('/content/drive/MyDrive/MSc/net/lane_list.npy')
lane_list = lane_list.tolist()

In [18]:
adj_mx = np.zeros((len(lane_list),len(lane_list)), dtype = np.float32)
adj_mx = np.array(adj_mx, dtype=np.float32)
print(adj_mx)
with open('/content/drive/MyDrive/MSc/net/adj_mx_0.pkl', 'wb') as f:
    pickle.dump([adj_mx, adj_mx, adj_mx], f, protocol=2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [27]:
class DetectorParse(handler.ContentHandler):
    """reading in the dataset from xml file
    """
    def __init__(self):
        self.adj_mx = np.eye(len(lane_list), dtype = np.float32)

    def startElement(self, name, attrs):
        if name == 'connection':
            fromedge = attrs['from']
            toedge = attrs['to']
            fromlane = attrs['from']+'_'+attrs['fromLane']
            tolane = attrs['to']+'_'+attrs['toLane']
            a = 7
            b = range(a)
            c = 3
            d = range(c)
            # connection between edges
            for i in reversed(b):
                if tolane+'%0' in lane_list:
                    if fromlane+'%'+str(i) in lane_list:
                        in_fromlane = lane_list.index(fromlane+'%'+str(i))
                        in_tolane = lane_list.index(tolane+'%0')
                        self.adj_mx[in_fromlane][in_tolane] = 1.00
                        break
            # connection in edges
            for i in reversed(b):
              for j in reversed(d):
                if fromedge+'_'+str(j)+'%'+str(i) in lane_list:
                  in_from = lane_list.index(fromedge+'_'+str(j)+'%'+str(i))
                  if fromedge+'_'+str(j+1)+'%'+str(i) in lane_list:      
                    in_to = lane_list.index(fromedge+'_'+str(j+1)+'%'+str(i))
                    self.adj_mx[in_from][in_to] = 1
                  if fromedge+'_'+str(j)+'%'+str(i+1) in lane_list:
                    in_to = lane_list.index(fromedge+'_'+str(j)+'%'+str(i+1))
                    self.adj_mx[in_from][in_to] = 1
                  if fromedge+'_'+str(j+1)+'%'+str(i+1) in lane_list:
                    in_to = lane_list.index(fromedge+'_'+str(j+1)+'%'+str(i+1))
                    self.adj_mx[in_from][in_to] = 1
        
    def endDocument(self):
        print(self.adj_mx)

In [31]:
class DetectorParse(handler.ContentHandler):
    """reading in the dataset from xml file
    """
    def __init__(self):
        self.adj_mx = np.zeros((len(lane_list),len(lane_list)), dtype = np.float32)

    def startElement(self, name, attrs):
        if name == 'connection':
            fromedge = attrs['from']
            toedge = attrs['to']
            fromlane = attrs['from']+'_'+attrs['fromLane']
            tolane = attrs['to']+'_'+attrs['toLane']
            a = 7
            b = range(a)
            c = 3
            d = range(c)
            # connection between edges
            for i in reversed(b):
                if tolane+'%0' in lane_list:
                    if fromlane+'%'+str(i) in lane_list:
                        in_fromlane = lane_list.index(fromlane+'%'+str(i))
                        in_tolane = lane_list.index(tolane+'%0')
                        self.adj_mx[in_fromlane][in_tolane] = 0.00
                        break
            # connection in edges
            for i in reversed(b):
              for j in reversed(d):
                if fromedge+'_'+str(j)+'%'+str(i) in lane_list:
                  in_from = lane_list.index(fromedge+'_'+str(j)+'%'+str(i))
                  if fromedge+'_'+str(j+1)+'%'+str(i) in lane_list:      
                    in_to = lane_list.index(fromedge+'_'+str(j+1)+'%'+str(i))
                    self.adj_mx[in_from][in_to] = 0
                  if fromedge+'_'+str(j)+'%'+str(i+1) in lane_list:
                    in_to = lane_list.index(fromedge+'_'+str(j)+'%'+str(i+1))
                    self.adj_mx[in_from][in_to] = 0
                  if fromedge+'_'+str(j+1)+'%'+str(i+1) in lane_list:
                    in_to = lane_list.index(fromedge+'_'+str(j+1)+'%'+str(i+1))
                    self.adj_mx[in_from][in_to] = 0
        
    def endDocument(self):
        print(self.adj_mx)

In [33]:
detector_output = DetectorParse()
parse('/content/drive/MyDrive/MSc/net/net.xml', detector_output) # reading in the dataset from xml file

# Save
with open('/content/drive/MyDrive/MSc/net/adj_mx_0.pkl', 'wb') as f:
    pickle.dump([detector_output.adj_mx[0], detector_output.adj_mx[0], detector_output.adj_mx], f, protocol=2)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
# lane_list # 630
load_npy = np.load('/content/drive/MyDrive/MSc/datasets/averagespeed/0617/d16.npy', allow_pickle=True)

lane_list = []
for i in range(len(load_npy)):  
  data = data_raw[i][1]
  if(len(data))==720:
    lane_list.append(load_npy[i][0])
'''
lane_list = []
for key in load_dict_1:
  if  key[0] != ':':
    lane_list.append(key)
'''
print(len(lane_list))

np.save('/content/drive/MyDrive/MSc/net/lane_list.npy', lane_list)

630


In [ ]:
data_raw = np.load('/content/drive/MyDrive/MSc/datasets/averagespeed/0617/d16.npy', allow_pickle=True)

In [ ]:
print(len(data_raw))

631


In [ ]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import argparse
import numpy as np
import pandas as pd
import pickle


def get_adjacency_matrix(distance_df, sensor_ids, normalized_k=0.1):
    """

    :param distance_df: data frame with three columns: [from, to, distance].
    :param sensor_ids: list of sensor ids.
    :param normalized_k: entries that become lower than normalized_k after normalization are set to zero for sparsity.
    :return:
    """
    num_sensors = len(sensor_ids)
    dist_mx = np.zeros((num_sensors, num_sensors), dtype=np.float32)
    dist_mx[:] = np.inf
    # Builds sensor id to index map.
    sensor_id_to_ind = {}
    '''
    for i, sensor_id in enumerate(sensor_ids):
        sensor_id_to_ind[sensor_id] = i

    # Fills cells in the matrix with distances.
    for row in distance_df.values:
        if row[0] not in sensor_id_to_ind or row[1] not in sensor_id_to_ind:
            continue
        dist_mx[sensor_id_to_ind[row[0]], sensor_id_to_ind[row[1]]] = row[2]

    # Calculates the standard deviation as theta.
    distances = dist_mx[~np.isinf(dist_mx)].flatten()
    std = distances.std()
    '''
    adj_mx = load_pickle('/content/drive/MyDrive/MSc/net/adj_mx_single.pkl')
    #adj_mx = np.exp(-np.square(dist_mx / std))
    # Make the adjacent matrix symmetric by taking the max.
    # adj_mx = np.maximum.reduce([adj_mx, adj_mx.T])

    # Sets entries that lower than a threshold, i.e., k, to zero for sparsity.
    #adj_mx[adj_mx < normalized_k] = 0
    sensor_ids = []
    return sensor_ids, sensor_id_to_ind, adj_mx


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    '''
    parser.add_argument('--sensor_ids_filename', type=str, default='/content/drive/MyDrive/MSc/net/lane_list.npy',
                        help='File containing sensor ids separated by comma.')
    parser.add_argument('--distances_filename', type=str, default='D:\ghr\SUMO\DCRNN-master\DCRNN-master\data/sensor_graph/distances_la_2012.csv',
                        help='CSV file containing sensor distances with three columns: [from, to, distance].')
    parser.add_argument('--normalized_k', type=float, default=0.1,
                        help='Entries that become lower than normalized_k after normalization are set to zero for sparsity.')
    parser.add_argument('--output_pkl_filename', type=str, default='D:\ghr\SUMO\DCRNN-master\DCRNN-master\data/sensor_graph/adj_mat.pkl',
                        help='Path of the output file.')
    '''
    args = parser.parse_args()

    with open(args.sensor_ids_filename) as f:
        sensor_ids = f.read().strip().split(',')
    distance_df = pd.read_csv(args.distances_filename, dtype={'from': 'str', 'to': 'str'})
    normalized_k = args.normalized_k
    _, sensor_id_to_ind, adj_mx = get_adjacency_matrix(distance_df, sensor_ids, normalized_k)
    # Save to pickle file.
    with open(args.output_pkl_filename, 'wb') as f:
        pickle.dump([sensor_ids, sensor_id_to_ind, adj_mx], f, protocol=2)


In [ ]:
    with open(args.output_pkl_filename, 'wb') as f:
        pickle.dump([sensor_ids, sensor_id_to_ind, adj_mx], f, protocol=2)